spring:
  application:
    name: spring-data-jpa-auditing-and-soft-delete

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
